### ISSUE TITLE
Error while running Main.py on Windows

### ISSUE THREAD

**Issue by lalitsanagavarapu** [SakisPap/Stix-2.0-Editor#6]
I am getting the following error, I am running it in Windows

%run "C:\Users\G50-70\Desktop\Stix-2.0-Editor-master\Stix-2.0-Editor-master\Main.py"
  File "C:\Users\G50-70\Desktop\Stix-2.0-Editor-master\Stix-2.0-Editor-master\Main.py", line 272
    editmenu.add_command(label="New Project...", command= lambda : [(welcomeLabel.pack_forget(), objects_page.pack(fill=tk.BOTH, expand=True), enableOptions()) if NewProject() else print("")])
                                                                                                                                                                                         ^
SyntaxError: invalid syntax

**Comment by SakisPap** [comment]
Thank you for your feedback Lalit Mohan Sanagavarapu,
this appears to be a versioning issue. Please make sure you are running Main.py with Python 3.6
