### ISSUE TITLE
macOS Mojave (10.14.1) support

### ISSUE THREAD

**Issue by CyberDaedalus00** [SakisPap/Stix-2.0-Editor#7]
attempting to execute the latest code on macOS Mojave, when you create a new project folder, the screen does not repaint with the list of icons and the console contains the following message:

objc[11964]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8b0c41d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10ff0cdc8). One of the two will be used. Which one is undefined.

**Comment by geosakel77** [comment]
It seems to be a Tk issue related to macOS Mojave. In order to furhter examine the issue, we will provide a dockerized version of the app, as soon as possible.
